var first_name="Ranbir";
var last_name="Kapoor";
console.log(first_name);
console.log(last_name);
var full_name=first_name.concat(last_name);
console.log(full_name);
var a=10;
var b=5;
var c=a+b;
console.log(a);
console.log(b);
console.log("10 + 5 = "+c);